
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out


running 6 tests
test benches::containts             ... bench:           0 ns/iter (+/- 0)
test benches::includes              ... FAILED
test benches::intersection          ... bench:          75 ns/iter (+/- 6)
test benches::nullable_containts    ... bench:           0 ns/iter (+/- 0)
test benches::nullable_includes     ... bench:          75 ns/iter (+/- 2)
test benches::nullable_intersection ... bench:          75 ns/iter (+/- 1)

failures:

---- benches::includes stdout ----
thread 'main' panicked at 'aaa!', benches/benchmark.rs:25:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    benches::includes

test result: FAILED. 0 passed; 1 failed; 0 ignored; 5 measured; 0 filtered out

